#!/usr/bin/env python3
"""Apply critical broker environment fixes.

This script generates the exact commands needed to fix the broker configuration.
For Replit deployments, outputs instructions for the Secrets UI.
For local/Docker, can write to .env.docker.

Usage:
    python scripts/apply_broker_fixes.py [--write-docker-env] [--show-exports]
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

CRITICAL_FIXES = {
    # CORS
    "CORS_ENABLED": "true",
    "CORS_ALLOW_ORIGINS": "https://fe266164-000d-4f21-9075-e118fb33ace0-00-1n10q5cqwcig7.picard.replit.dev",
    
    # Features
    "QUOTES_ENABLED": "true",
    "PURCHASES_ENABLED": "true",
    
    # Payments
    "TREASURY_ADDRESS": "0xe6e24e8E6F3004D82F0C710f6Bb035af1bE730C1",
    "USDC_ADDRESS": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "ACCEPT_ASSETS": "ETH,USDC",
    
    # Pricing Route
    "TRADE_PATH": "0xf4d97f2da56e8c3098f3a8d538db630a2606a024@3000,0x4200000000000000000000000000000000000006@500,0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "TRADE_PATHS_DYNAMIC": "false",
    
    # DEX Tuning
    "DEX_PROVIDER_TIMEOUT_SECONDS": "2.5",
    "DEX_AGGREGATOR_MAX_WORKERS": "3",
    
    # Token Addresses
    "VVV_TOKEN_ADDRESS": "0xacfE6019Ed1A7Dc6f7B508C02d1b04ec88cC21bf",
    "DIEM_TOKEN_ADDRESS": "0xf4d97f2da56e8c3098f3a8d538db630a2606a024",
    "QUOTE_TOKEN_ADDRESS": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "WETH_ADDRESS": "0x4200000000000000000000000000000000000006",
    
    # Debug
    "MARKETDATA_DEBUG_SANITY": "1",
}

OPTIONAL_FIXES = {
    "VVV_TRADE_PATH": "0xacfE6019Ed1A7Dc6f7B508C02d1b04ec88cC21bf@3000,0x4200000000000000000000000000000000000006@500,0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
    "UNISWAP_V3_DEFAULT_FEE": "3000",
    "DIEM_DEBUG_ROUTES": "1",
}


def main():
    repo_root = Path(__file__).resolve().parents[1]
    docker_env_path = repo_root / ".env.docker"
    
    write_docker = "--write-docker-env" in sys.argv
    show_exports = "--show-exports" in sys.argv
    
    print("=" * 70)
    print("Venice Broker - Critical Environment Fixes")
    print("=" * 70)
    print()
    
    if write_docker:
        print(f"Writing to: {docker_env_path}")
        print()
        
        with docker_env_path.open("w", encoding="utf-8") as f:
            f.write("# Venice Broker - Critical Environment Fixes\n")
            f.write(f"# Generated: {__import__('datetime').datetime.now().isoformat()}\n")
            f.write("# Auto-generated by scripts/apply_broker_fixes.py\n\n")
            
            f.write("# CRITICAL FIXES\n")
            for key, value in CRITICAL_FIXES.items():
                f.write(f"{key}={value}\n")
            
            f.write("\n# OPTIONAL (recommended)\n")
            for key, value in OPTIONAL_FIXES.items():
                f.write(f"{key}={value}\n")
        
        print(f"✓ Wrote {len(CRITICAL_FIXES) + len(OPTIONAL_FIXES)} variables to {docker_env_path}")
        print()
        print("Next steps:")
        print("  1. Review the file: cat .env.docker")
        print("  2. Restart your deployment")
        print("  3. Run validation: python scripts/validate_broker_env.py")
        print()
        
    elif show_exports:
        print("Export statements (copy/paste into your shell):")
        print()
        for key, value in CRITICAL_FIXES.items():
            safe_value = value.replace('"', '\\"').replace('$', '\\$')
            print(f'export {key}="{safe_value}"')
        print()
        print("# Optional:")
        for key, value in OPTIONAL_FIXES.items():
            safe_value = value.replace('"', '\\"').replace('$', '\\$')
            print(f'export {key}="{safe_value}"')
        print()
        
    else:
        print("For Replit Deployment:")
        print("-" * 70)
        print("1. Open your Repl → Secrets panel (lock icon in sidebar)")
        print("2. Add or update the following variables:")
        print()
        
        print("CRITICAL (must set all):")
        for idx, (key, value) in enumerate(CRITICAL_FIXES.items(), 1):
            status = "✓ SET" if os.getenv(key) == value else ("⚠ DIFFERENT" if os.getenv(key) else "✗ MISSING")
            print(f"  {idx:2}. {key:<35} = {value}")
            print(f"      Current: {status}")
        
        print()
        print("OPTIONAL (recommended):")
        for key, value in OPTIONAL_FIXES.items():
            status = "✓ SET" if os.getenv(key) == value else ("⚠ DIFFERENT" if os.getenv(key) else "✗ MISSING")
            print(f"  - {key:<35} = {value}")
            print(f"    Current: {status}")
        
        print()
        print("-" * 70)
        print("3. After updating secrets, restart your deployment:")
        print("   - Click Stop, then Run")
        print("   - Or: pkill -f 'broker-api' (if using background process)")
        print()
        print("4. Verify the fixes:")
        print("   python scripts/validate_broker_env.py")
        print("   bash scripts/smoke_test_broker.sh")
        print()
        print("=" * 70)
        print()
        print("Options:")
        print("  --write-docker-env   Write to .env.docker for local/Docker deployments")
        print("  --show-exports       Print export statements for current shell")


if __name__ == "__main__":
    main()

